services:
  nearbydb:
    image: mysql:8.0.27
    platform: linux/amd64
    container_name: nearbyContainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: reportsFeed
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Jaimatadi
      SERVICE_TAG: dev
      SERVICE_NAME: nearbydb
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappContainer
    build: .
    image: nodeapp:v1
    platform: linux/amd64
    volumes:
      - $HOME/nodeapp:/code
    ports:
      - 3000:3000 
    expose:
      - 3000
    environment:
      DB_HOST : nearbydb
      DB_PORT : 3306
      DB_USER : root
      DB_NAME :  reportsFeed
      DB_PASSWORD : Jaimatadi
      SERVICE_TAG: dev
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 3000
    depends_on:
      - nearbydb
    networks:
      - internalnet


networks:
  internalnet:
    driver: bridge

